-- 코드를 입력하세요
SELECT
    WAREHOUSE_ID,
    WAREHOUSE_NAME,
    ADDRESS,
    CASE
        WHEN FREEZER_YN IS NULL THEN 'N'
        WHEN FREEZER_YN IS NOT NULL THEN FREEZER_YN
    END AS FREEZER_YN
FROM FOOD_WAREHOUSE
    WHERE ADDRESS LIKE ('경기%')
    order by WAREHOUSE_ID ASC;